---
title: "00.Fig.SOX4"
---

```{r knitr, include = FALSE}
DOCNAME <- "00.Fig.SOX4"
dir.create(here::here("output", DOCNAME), showWarnings = FALSE)

NOW <- Sys.time()
# Time chunks during knitting
knitr::knit_hooks$set(timeit = function(before) {
  if (before) {
    print(paste("Start:", Sys.time()))
    NOW <<- Sys.time()
  } else {
    print(paste("Stop:", Sys.time()))
    print(Sys.time() - NOW)
  }
})

knitr::opts_chunk$set(
  autodep        = TRUE,
  cache          = FALSE,
  cache.path     = paste0("cache/", DOCNAME, "/"),
  cache.lazy     = FALSE,
  cache.comments = FALSE,
  echo           = TRUE,
  error          = FALSE,
  fig.align      = "center",
  fig.width      = 10,
  fig.height     = 8,
  message        = FALSE,
  warning        = FALSE,
  timeit         = TRUE
)
```

## Setup

Load packages

```{r libaries, cache = FALSE, message=FALSE, warning=FALSE}
# Tidyverse
library(tidyverse)

# Plotting
library(scales)
library(EnvStats)
library(ggplotify)
library(ggcorrplot)
library(corrplot)
library(ggpubr)
library(ggrepel)
library(ggrastr)
library(UpSetR)

# patch
library(patchwork)
library(cowplot)
my_theme <- theme_cowplot(
  font_size = 6, # Overall font size
  rel_small = 6 / 6, # axis tick labels
  rel_tiny = 6 / 6, # caption
  rel_large = 6 / 6 # title
)
geom.text.size <- 6 / (14 / 5)

# heatmap
library(pheatmap)
library(ComplexHeatmap)

# color
library(ggsci)

# Seurat
library(Seurat)

# vis
library(scRNAtoolVis)

# enrichment
library(clusterProfiler)
library(org.Hs.eg.db)
```

Load code

```{r source, cache = FALSE}
source(here::here("code/preprocess.R"))
source(here::here("code/glm.R"))
source(here::here("code/color.R"))
source(here::here("code/plot.R"))
```

## Load data

Get Td-types cells

```{r}
td_types <- readRDS(here::here("output", "00.Fig.Td-type", "td_types.rds"))
```

Cluster to celltypes

```{r message=FALSE, warning=FALSE}
df_c2c <- readRDS(here::here("data", "cluster_2_celltype.ALL.orderByLevel3.rds"))
```

## SOX4 exp rank in all cellType3

Load rds

```{r eval=FALSE}
srat <- readRDS(here::here("output", "04.rm_cells", "seurat.rds"))
Idents(srat) <- "cellType3"
srat
```

Get exp

```{r eval=FALSE}
e <- AverageExpression(srat,
  assays = "RNA", features = "SOX4",
  slot = "data", verbose = F
)$RNA
e <- log1p(e)

# df
df_exp <- t(e) %>%
  as.data.frame() %>%
  rownames_to_column("cellType3") %>%
  arrange(-SOX4) %>%
  mutate(rank = 1:length(SOX4))
saveRDS(df_exp, file = here::here("output", DOCNAME, "df.SOX4_exp.rds"))
df_exp %>%
  write_tsv(file = here::here("output", DOCNAME, "df.SOX4_exp.tsv"))
```

```{r}
df_exp <- readRDS(here::here("output", DOCNAME, "df.SOX4_exp.rds")) %>% 
  mutate(
    cellType3 = case_when(
      cellType3 == "normal lymphatics" ~ "LEC-C1",
      cellType3 == "tumor lymphatics" ~ "LEC-C2",
      TRUE ~ cellType3
    )
  )
```

Plot

```{r fig.width=6, fig.height=6}
d4p <- df_exp %>%
  mutate(td_types = case_when(
    cellType3 %in% td_types$level_3 ~ "Yes",
    str_starts(cellType3, "Epi") ~ "No",
    TRUE ~ "No"
  )) %>%
  mutate(td_types = factor(td_types, levels = c("Yes", "No")))

d4p_label <- d4p %>%
  filter(td_types == "Yes") %>% 
  filter(!str_starts(cellType3, "Epi"))

p <- d4p %>%
  ggplot(aes(x = rank, y = SOX4, color = td_types)) +
  geom_point(size = 2) +
  geom_text_repel(
    data = d4p_label, aes(x = rank, y = SOX4, label = cellType3),
    # color = "red",
    inherit.aes = FALSE,
    max.overlaps = 100,
    size = geom.text.size
  ) +
  scale_color_manual(values = rev(colors_2)) +
  labs(x = "Rank", y = "Normalized exp. of SOX4") +
  my_theme +
  theme(legend.position = c(.8, .8))
p

ggsave2(
  filename = here::here("output", DOCNAME, "Fig.SOX4_exp_cellType3.pdf"),
  height = 6, width = 6
)
```

## SOX4 exp. and TF activity

Get SOX4 TF activity

```{r message=FALSE, warning=FALSE, eval=FALSE}
# get mean TF activity of cellType3
get_tf_activity <- function(cell = NULL, level = NULL) {
  aucell_res_path <- "/work/home/project/scESCA/pySCENIC/200227_6samples"
  aucell_tf <- read_csv(file.path(aucell_res_path, paste0(paste0("seurat_", cell), ".TF.auc_mtx.csv"))) %>%
    mutate(Regulon = str_replace(Regulon, "[(][+][)]", "")) %>%
    filter(Regulon == "SOX4") %>%
    column_to_rownames(var = "Regulon") %>%
    t() %>%
    as.data.frame() %>%
    rownames_to_column("barcode")
  meta <- read_csv(here::here("output/04.rm_cells", paste0(paste0("seurat_", cell), ".cellmeta.csv"))) %>%
    dplyr::select(barcode, cellType3 = !!sym(level))
  aucell_tf %>%
    left_join(meta, by = "barcode") %>%
    group_by(cellType3) %>%
    summarise(SOX4_TF = mean(SOX4))
}

# cells
df_tf_lst <- list(
  bcells = get_tf_activity(cell = "bcells", level = "level_2") %>% mutate(cellType3 = paste0("B-", cellType3)),
  cd4 = get_tf_activity(cell = "cd4.random1", level = "level_3"),
  cd8 = get_tf_activity(cell = "cd8.random1", level = "level_3"),
  endo = get_tf_activity(cell = "endothelia", level = "level_2"),
  epi = get_tf_activity(cell = "epithelia", level = "level_1"),
  fib = get_tf_activity(cell = "fibroblasts", level = "level_3"),
  mye = get_tf_activity(cell = "myeloid", level = "level_3"),
  treg = get_tf_activity(cell = "treg", level = "level_3")
)

# combine all cells
df_tf = do.call(rbind, df_tf_lst)
saveRDS(df_tf, file = here::here("output", DOCNAME, "df.SOX4_tf.rds"))
df_tf %>%
  write_tsv(file = here::here("output", DOCNAME, "df.SOX4_tf.tsv"))
```

```{r}
df_tf <- readRDS(here::here("output", DOCNAME, "df.SOX4_tf.rds"))
```

Plot

```{r fig.width=10, fig.height=6}
d4p = df_exp %>%
  right_join(df_tf, by = "cellType3") %>% 
  left_join(df_c2c %>% mutate(cellType3 = level_3), by = "cellType3") %>%
  dplyr::select(cell, cellType3, SOX4, SOX4_TF) %>%
  
  mutate(td_types = case_when(
    cellType3 %in% td_types$level_3 ~ "Yes",
    TRUE ~ "No"
  )) %>%
  mutate(td_types = factor(td_types, levels = c("Yes", "No")))

d4p_label <- d4p %>%
  filter(td_types == "Yes")

d4p %>%
  ggplot(aes(x = SOX4, y = SOX4_TF, color = td_types)) +
  geom_point(size = 2) +
  geom_text_repel(
    data = d4p_label, aes(x = SOX4, y = SOX4_TF, label = cellType3),
    # color = "red",
    inherit.aes = FALSE,
    max.overlaps = 100,
    size = geom.text.size
  ) +
  scale_color_manual(values = rev(colors_2)) +
  labs(x = "Mean SOX4 exp.", y = "Mean SOX4 TF act.") +
  facet_wrap(.~cell, scales = "free") +
  my_theme

ggsave2(
  filename = here::here("output", DOCNAME, "Fig.SOX4_exp_tf_cellType3.pdf"),
  width = 10, height = 6
)
```

## Genes correlated with SOX4 {.tabset}

### Endothelia

```{r message=FALSE, warning=FALSE, fig.width=7, fig.height=5}
a = 'endo'
fname = paste0(paste0("df.SOX4_cor_genes.", a), '.tsv')
tb = read_tsv(here::here("output", DOCNAME, fname))
tb_top = tb %>%
  filter(gene != "SOX4") %>%
  group_by(level_3) %>%
  slice_max(n = 100, order_by = corrs)

# save
tb_top %>%
  write_tsv(here::here("output", DOCNAME, paste0(paste0("df.SOX4_cor_genes.", a), '.top100.tsv')))

gene_lst = split(tb_top$gene, tb_top$level_3)
upset(fromList(gene_lst),
      nsets = length(gene_lst),
      nintersects = 100,
      show.numbers = FALSE,
      #sets.bar.color = pop_color_maps[super_pops],
      point.size = 1, line.size = 0.3,
      mb.ratio = c(0.5, 0.5))
```

```{r message=FALSE, warning=FALSE, fig.width=7, fig.height=5}
compareList = lapply(gene_lst, function(x){
  bitr(x, fromType="SYMBOL", toType=c("ENTREZID"), OrgDb="org.Hs.eg.db")[,2]
})

ck = compareCluster(compareList, fun = "enrichKEGG", organism = "hsa",
                    use_internal_data = TRUE,
                    pvalueCutoff = 0.05)
cg.BP = compareCluster(compareList, fun = "enrichGO", OrgDb = org.Hs.eg.db, ont = "BP",
                       pAdjustMethod = "BH", pvalueCutoff = 0.01, qvalueCutoff = 0.05,
                       readable = T)

# save
write.table(cg.BP, file = here::here('output', DOCNAME, paste0(paste0("df.SOX4_cor_genes.", a), '.top100.BP.tsv')),
            sep="\t", quote=F, row.names=F)
write.table(ck, file = here::here('output', DOCNAME, paste0(paste0("df.SOX4_cor_genes.", a), '.top100.KEGG.tsv')),
            sep="\t", quote=F, row.names=F)
```

```{r , fig.width=8, fig.height=6}
dotplot(ck) + 
  scale_size(range = c(0, 5)) + 
  scale_y_discrete(labels = function(x) str_wrap(x, width = 60)) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
```

```{r , fig.width=8, fig.height=7}
dotplot(cg.BP) + 
  scale_y_discrete(labels = function(x) str_wrap(x, width = 60)) + 
  scale_size(range = c(0, 5)) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
```

### Fibroblasts

```{r message=FALSE, warning=FALSE, fig.width=8, fig.height=6}
a = 'fib'
fname = paste0(paste0("df.SOX4_cor_genes.", a), '.tsv')
tb = read_tsv(here::here("output", DOCNAME, fname))
tb_top = tb %>%
  filter(gene != "SOX4") %>%
  group_by(level_3) %>%
  slice_max(n = 100, order_by = corrs)

# save
tb_top %>%
  write_tsv(here::here("output", DOCNAME, paste0(paste0("df.SOX4_cor_genes.", a), '.top100.tsv')))

gene_lst = split(tb_top$gene, tb_top$level_3)
upset(fromList(gene_lst),
      nsets = length(gene_lst),
      nintersects = 100,
      show.numbers = FALSE,
      #sets.bar.color = pop_color_maps[super_pops],
      point.size = 1, line.size = 0.3,
      mb.ratio = c(0.5, 0.5))
```

```{r message=FALSE, warning=FALSE, fig.width=7, fig.height=5}
compareList = lapply(gene_lst, function(x){
  bitr(x, fromType="SYMBOL", toType=c("ENTREZID"), OrgDb="org.Hs.eg.db")[,2]
})

ck = compareCluster(compareList, fun = "enrichKEGG", organism = "hsa",
                    use_internal_data = TRUE,
                    pvalueCutoff = 0.05)
cg.BP = compareCluster(compareList, fun = "enrichGO", OrgDb = org.Hs.eg.db, ont = "BP",
                       pAdjustMethod = "BH", pvalueCutoff = 0.01, qvalueCutoff = 0.05,
                       readable = T)

# save
write.table(cg.BP, file = here::here('output', DOCNAME, paste0(paste0("df.SOX4_cor_genes.", a), '.top100.BP.tsv')),
            sep="\t", quote=F, row.names=F)
write.table(ck, file = here::here('output', DOCNAME, paste0(paste0("df.SOX4_cor_genes.", a), '.top100.KEGG.tsv')),
            sep="\t", quote=F, row.names=F)
```

```{r , fig.width=8.5, fig.height=6}
dotplot(ck) + 
  scale_size(range = c(0, 5)) + 
  scale_y_discrete(labels = function(x) str_wrap(x, width = 60)) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
```

```{r , fig.width=9, fig.height=7}
dotplot(cg.BP) + 
  scale_y_discrete(labels = function(x) str_wrap(x, width = 60)) + 
  scale_size(range = c(0, 5)) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
```

### Epithelia

```{r message=FALSE, warning=FALSE, fig.width=8, fig.height=6}
a = 'epi'
fname = paste0(paste0("df.SOX4_cor_genes.", a), '.tsv')
tb = read_tsv(here::here("output", DOCNAME, fname))
tb_top = tb %>%
  filter(gene != "SOX4") %>%
  group_by(level_3) %>%
  slice_max(n = 100, order_by = corrs)

# save
tb_top %>%
  write_tsv(here::here("output", DOCNAME, paste0(paste0("df.SOX4_cor_genes.", a), '.top100.tsv')))

gene_lst = split(tb_top$gene, tb_top$level_3)
upset(fromList(gene_lst),
      nsets = length(gene_lst),
      nintersects = 100,
      show.numbers = FALSE,
      #sets.bar.color = pop_color_maps[super_pops],
      point.size = 1, line.size = 0.3,
      mb.ratio = c(0.5, 0.5))
```

```{r message=FALSE, warning=FALSE, fig.width=7, fig.height=5}
compareList = lapply(gene_lst, function(x){
  bitr(x, fromType="SYMBOL", toType=c("ENTREZID"), OrgDb="org.Hs.eg.db")[,2]
})

ck = compareCluster(compareList, fun = "enrichKEGG", organism = "hsa",
                    use_internal_data = TRUE,
                    pvalueCutoff = 0.05)
cg.BP = compareCluster(compareList, fun = "enrichGO", OrgDb = org.Hs.eg.db, ont = "BP",
                       pAdjustMethod = "BH", pvalueCutoff = 0.01, qvalueCutoff = 0.05,
                       readable = T)

# save
write.table(cg.BP, file = here::here('output', DOCNAME, paste0(paste0("df.SOX4_cor_genes.", a), '.top100.BP.tsv')),
            sep="\t", quote=F, row.names=F)
write.table(ck, file = here::here('output', DOCNAME, paste0(paste0("df.SOX4_cor_genes.", a), '.top100.KEGG.tsv')),
            sep="\t", quote=F, row.names=F)
```

```{r , fig.width=8.5, fig.height=6}
dotplot(ck) + 
  scale_size(range = c(0, 5)) + 
  scale_y_discrete(labels = function(x) str_wrap(x, width = 60)) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
```

```{r , fig.width=9, fig.height=7}
dotplot(cg.BP) + 
  scale_y_discrete(labels = function(x) str_wrap(x, width = 60)) + 
  scale_size(range = c(0, 5)) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
```

### Myeloid

```{r message=FALSE, warning=FALSE, fig.width=8, fig.height=6}
a = 'mye'
fname = paste0(paste0("df.SOX4_cor_genes.", a), '.tsv')
tb = read_tsv(here::here("output", DOCNAME, fname))
tb_top = tb %>%
  filter(gene != "SOX4") %>%
  group_by(level_3) %>%
  slice_max(n = 100, order_by = corrs)

# save
tb_top %>%
  write_tsv(here::here("output", DOCNAME, paste0(paste0("df.SOX4_cor_genes.", a), '.top100.tsv')))

gene_lst = split(tb_top$gene, tb_top$level_3)
upset(fromList(gene_lst),
      nsets = length(gene_lst),
      nintersects = 100,
      show.numbers = FALSE,
      #sets.bar.color = pop_color_maps[super_pops],
      point.size = 1, line.size = 0.3,
      mb.ratio = c(0.5, 0.5))
```

ORA

```{r message=FALSE, warning=FALSE, fig.width=7, fig.height=5}
compareList = lapply(gene_lst, function(x){
  bitr(x, fromType="SYMBOL", toType=c("ENTREZID"), OrgDb="org.Hs.eg.db")[,2]
})

ck = compareCluster(compareList, fun = "enrichKEGG", organism = "hsa",
                    use_internal_data = TRUE,
                    pvalueCutoff = 0.05)
cg.BP = compareCluster(compareList, fun = "enrichGO", OrgDb = org.Hs.eg.db, ont = "BP",
                       pAdjustMethod = "BH", pvalueCutoff = 0.01, qvalueCutoff = 0.05,
                       readable = T)

# save
write.table(cg.BP, file = here::here('output', DOCNAME, paste0(paste0("df.SOX4_cor_genes.", a), '.top100.BP.tsv')),
            sep="\t", quote=F, row.names=F)
write.table(ck, file = here::here('output', DOCNAME, paste0(paste0("df.SOX4_cor_genes.", a), '.top100.KEGG.tsv')),
            sep="\t", quote=F, row.names=F)
```

```{r , fig.width=8.5, fig.height=6}
dotplot(ck) + 
  scale_size(range = c(0, 5)) + 
  scale_y_discrete(labels = function(x) str_wrap(x, width = 60)) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
```

```{r , fig.width=6, fig.height=4}
dotplot(cg.BP) + 
  scale_y_discrete(labels = function(x) str_wrap(x, width = 60)) + 
  scale_size(range = c(0, 5)) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
```

### Tcell

```{r message=FALSE, warning=FALSE, fig.width=7, fig.height=5}
a = 't'
fname = paste0(paste0("df.SOX4_cor_genes.", a), '.tsv')
tb = read_tsv(here::here("output", DOCNAME, fname))
tb_top = tb %>%
  filter(gene != "SOX4") %>%
  group_by(level_3) %>%
  slice_max(n = 100, order_by = corrs)

# save
tb_top %>%
  write_tsv(here::here("output", DOCNAME, paste0(paste0("df.SOX4_cor_genes.", a), '.top100.tsv')))

gene_lst = split(tb_top$gene, tb_top$level_3)
upset(fromList(gene_lst),
      nsets = length(gene_lst),
      nintersects = 100,
      show.numbers = FALSE,
      #sets.bar.color = pop_color_maps[super_pops],
      point.size = 1, line.size = 0.3,
      mb.ratio = c(0.5, 0.5))
```

ORA

```{r message=FALSE, warning=FALSE, fig.width=7, fig.height=5}
compareList = lapply(gene_lst, function(x){
  bitr(x, fromType="SYMBOL", toType=c("ENTREZID"), OrgDb="org.Hs.eg.db")[,2]
})

ck = compareCluster(compareList, fun = "enrichKEGG", organism = "hsa",
                    use_internal_data = TRUE,
                    pvalueCutoff = 0.05)
cg.BP = compareCluster(compareList, fun = "enrichGO", OrgDb = org.Hs.eg.db, ont = "BP",
                       pAdjustMethod = "BH", pvalueCutoff = 0.01, qvalueCutoff = 0.05,
                       readable = T)

# save
write.table(cg.BP, file = here::here('output', DOCNAME, paste0(paste0("df.SOX4_cor_genes.", a), '.top100.BP.tsv')),
            sep="\t", quote=F, row.names=F)
write.table(ck, file = here::here('output', DOCNAME, paste0(paste0("df.SOX4_cor_genes.", a), '.top100.KEGG.tsv')),
            sep="\t", quote=F, row.names=F)
```

```{r , fig.width=8.5, fig.height=6}
dotplot(ck) + 
  scale_size(range = c(0, 5)) + 
  scale_y_discrete(labels = function(x) str_wrap(x, width = 60)) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
```

```{r , fig.width=8, fig.height=6}
dotplot(cg.BP) + 
  scale_y_discrete(labels = function(x) str_wrap(x, width = 60)) + 
  scale_size(range = c(0, 5)) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
```



## Session info
