---
title: "00.Fig.tcells.CD4"
---

```{r knitr, include = FALSE}
DOCNAME <- "00.Fig.tcells.CD4"
dir.create(here::here("output", DOCNAME), showWarnings = FALSE)

NOW <- Sys.time()
# Time chunks during knitting
knitr::knit_hooks$set(timeit = function(before) {
  if (before) {
    print(paste("Start:", Sys.time()))
    NOW <<- Sys.time()
  } else {
    print(paste("Stop:", Sys.time()))
    print(Sys.time() - NOW)
  }
})

knitr::opts_chunk$set(
  autodep        = TRUE,
  cache          = FALSE,
  cache.path     = paste0("cache/", DOCNAME, "/"),
  cache.lazy     = FALSE,
  cache.comments = FALSE,
  echo           = FALSE,
  error          = FALSE,
  fig.align      = "center",
  fig.width      = 10,
  fig.height     = 8,
  message        = FALSE,
  warning        = FALSE,
  timeit         = TRUE
)
```

## Setup

Load packages

```{r libaries, cache = FALSE, message=FALSE, warning=FALSE}
# Tidyverse
library(tidyverse)

# Plotting
library(scales)
library(EnvStats)
library(ggplotify)
library(ggcorrplot)
library(ggpubr)
library(ggrepel)
library(ggrastr)

# patch
library(patchwork)
library(cowplot)
theme_set(theme_cowplot(
  font_size = 6, # Overall font size
  rel_small = 6 / 6, # axis tick labels
  rel_tiny = 6 / 6, # caption
  rel_large = 6 / 6 # title
))
my_theme <- theme_cowplot(
  font_size = 6, # Overall font size
  rel_small = 6 / 6, # axis tick labels
  rel_tiny = 6 / 6, # caption
  rel_large = 6 / 6 # title
)
geom.text.size <- 6 / (14 / 5)

# heatmap
library(pheatmap)
library(ComplexHeatmap)

# color
library(ggsci)

# pvclust
library(pvclust)
library(dendextend)

# Seurat
library(Seurat)

# monocle
library(monocle)

# CytoTRACE
library(CytoTRACE)
```

Load code

```{r source, cache = FALSE}
source(here::here("code/preprocess.R"))
source(here::here("code/glm.R"))
source(here::here("code/color.R"))
source(here::here("code/plot.R"))
devtools::load_all(here::here("code/Rscir"))
```

Load rds

```{r load-rds, cache=FALSE}
srat <- readRDS(here::here("output/04.rm_cells/seurat_cd4_treg.rds"))
Idents(srat) <- "level_3"
srat
```

Load cell meta

```{r load-cell-meta, cache=FALSE, message=FALSE, warning=FALSE}
cell_meta <- read_csv(here::here("output/04.rm_cells/seurat_cd4_treg.cellmeta.csv")) %>%
  dplyr::select(barcode, Origin2_n, seurat_clusters, level_2, level_3)
head(cell_meta)
```

Cell annotations

```{r anno, cache=FALSE}
df.c2c <- readRDS(here::here("data", "c2c.t.rds"))
head(df.c2c)
```

## Functional signaturess

Use `AddModuleScore` to get program scores of each cell

```{r , fig.width=7.5, fig.height=3}
markers <- list(
  # TCA cycle
  TCA_cycle = filter_features(srat, c("ACLY", "ACO1", "ACO2", "CS", "DLAT", "DLD", "DLST", "FH", "IDH1", "IDH2", "IDH3A", "IDH3B", "IDH3G", "MDH1", "MDH1B", "MDH2", "OGDH", "PC", "PCK1PCK2", "PDHA1", "PDHB", "SDHA", "SDHB", "SDHD", "SUCLA2", "SUCLG1", "SUCLG2")),
  # Glycolysis
  Glycolysis = filter_features(srat, c("ALDOA", "ALDOB", "ALDOC", "BPGM", "ENO1", "ENO2", "GALM", "GCK", "GPI", "HK2", "HK3", "PFKL", "PGAM2", "PGK1", "PGK2", "PGM1", "PGM2", "PGM3", "PKLR", "TPI1")),
  # Pentose Phosphate Pathway
  Pentose_phos = filter_features(srat, c("G6PD", "6PD", "PGLS", "PRPS1", "PRPS1L1", "PRPS2", "RBKS", "RPE", "RPIA", "TALDO1", "TKT")),
  # Glycogen Metabolism
  Glycogen_metabo = filter_features(srat, c("GBE1", "GYS1", "GYS2", "UGP2", "AGL", "PGM1", "PGM2", "PGM3", "PYGL", "PYGM", "GSK3A", "GSK3B", "PHKA1", "PHKB", "PHKG1", "PHKG2")),
  # Lipid mediators
  Lipid_mediators = filter_features(srat, c("ADIPOQ", "CD137", "AgRP", "ANGPT1", "ANGPT2", "ANGPTL3", "ANGPTL4", "ANGPTL6", "BAFF", "BMP4", "CTSD", "CTSS", "CCL2", "CCL5", "RARRES2", "CFD", "CRP", "CXCL8", "CD26", "ESM1", "S100A12", "AHSG", "FGF1", "FGF2", "FGF21", "FGF23", "LGALS3", "GCG", "GH1", "HGF", "ICAM1", "IGFBP1", "IGFBP2", "IGFBP3", "IGFBP4", "IGFBP6", "IGFBP7", "IL1b", "IL6", "IL10", "IL11", "INS", "LEP", "LIF", "NGAL", "MCSF", "MIF", "MPO", "GHRL", "GHSR", "LIPE", "LPL", "AGT", "CEBPA", "CFD", "FABP4", "FASN", "IRS2", "KLF15", "PPARG", "PPARGC1A", "RETN", "SRT3", "SLC2A4", "SREBF1", "ACACB", "AXIN1", "CCND1", "CDK4", "CEBPB", "CEBPD", "DKK1", "E2F1", "FABP4", "FASN")),
  # Glucose Deprivation
  Glucose_deprivation = filter_features(srat, c("NRN1", "FAM129A", "1L23A", "SPRY1", "GADD45B", "HSPA1A/B", "GPNMB", "HAVCR2", "SOAT2", "ADAMTS6")),
  # G1/S
  G1S = filter_features(srat, c("BRCA1", "BRCA2", "CCNE1", "CCNE2", "CCNG2", "CDC25A", "CDC45", "CDC6", "CDKN1A", "CDKN2C", "CDKN3", "DHFR", "E2F1", "E2F5", "H1F0", "H1FNT", "H1FOO", "H1FX", "H2AFB1", "H2AFB2", "H2AFB3", "H2AFJ", "H2AFV", "H2AFVP1", "H2AFX", "H2AFY", "H2AFY2", "H2AFZ", "H2AFZP1", "H2AFZP2", "H2AFZP3", "H2AFZP4", "H2AFZP5", "H2AFZP6", "H2BFM", "H2BFS", "H2BFWT", "H2BFXP", "H3F3A", "H3F3AP1", "H3F3AP2", "H3F3B", "H3F3C", "HIST1H1A", "HIST1H1B", "HIST1H1C", "HIST1H1D", "HIST1H1E", "HIST1H1PS1", "HIST1H1PS2", "HIST1H1T", "HIST1H2AA", "HIST1H2AB", "HIST1H2AC", "HIST1H2AD", "HIST1H2AE", "HIST1H2AG", "HIST1H2AH", "HIST1H2AI", "HIST1H2AJ", "HIST1H2AK", "HIST1H2AL", "HIST1H2AM", "HIST1H2APS1", "HIST1H2APS2", "HIST1H2APS3", "HIST1H2APS4", "HIST1H2APS5", "HIST1H2BA", "HIST1H2BB", "HIST1H2BC", "HIST1H2BD", "HIST1H2BE", "HIST1H2BF", "HIST1H2BG", "HIST1H2BH", "HIST1H2BI", "HIST1H2BJ", "HIST1H2BK", "HIST1H2BL", "HIST1H2BM", "HIST1H2BN", "HIST1H2BO", "HIST1H2BPS1", "HIST1H2BPS2", "HIST1H3A", "HIST1H3B", "HIST1H3C", "HIST1H3D", "HIST1H3E", "HIST1H3F", "HIST1H3G", "HIST1H3H", "HIST1H3I", "HIST1H3J", "HIST1H3PS1", "HIST1H4A", "HIST1H4B", "HIST1H4C", "HIST1H4D", "HIST1H4E", "HIST1H4F", "HIST1H4G", "HIST1H4H", "HIST1H4I", "HIST1H4J", "HIST1H4K", "HIST1H4L", "HIST1H4PS1", "HIST2H2AA3", "HIST2H2AA4", "HIST2H2AB", "HIST2H2AC", "HIST2H2BA", "HIST2H2BB", "HIST2H2BC", "HIST2H2BD", "HIST2H2BE", "HIST2H2BF", "HIST2H3A", "HIST2H3C", "HIST2H3D", "HIST2H3PS2", "HIST2H4A", "HIST2H4B", "HIST3H2A", "HIST3H2BA", "HIST3H2BB", "HIST3H3", "HIST4H4", "MCM2", "MCM6", "MSH2", "NASP", "NPAT", "PCNA", "RRM1", "RRM2", "SLBP", "TYMS")),
  # G2M
  G2M = filter_features(srat, c("AURKA", "BIRC5", "BUB1", "BUB1B", "CCNA2", "CCNB1", "CCNB2", "CCNF", "CDC20", "CDC25B", "CDC25C", "CDK1", "CDKN2D", "CENPA", "CENPF", "CKS2", "KIF20A", "PLK1", "RACGAP1", "TOP2A")),
  # hypoxia
  Hypoxia = filter_features(srat, c("AL2", "ALDOA", "AM", "BCL2", "BCL2L1", "FOS", "JUN", "SRC", "CBP", "CCR6", "CEBPB", "ENOLAS", "FAS", "FASLG", "FKBP52", "GAPDH", "GLUT1", "GLUT3", "CSF2", "IFNG", "IFNB1", "IL13", "IL1R1", "IL2RA", "IL4", "IL5", "IL6R", "IL8", "IL10R", "IL15R", "ITGA6", "ITK", "JUN D", "CLB54", "MAP3K5", "MAP2K1", "MAP2K2", "MIF", "NFATC1", "NFKB2", "NFKBIE", "P53", "TGM6", "TNF", "TNFRSF1B", "TRADD", "TRAIL", "TRAP1", "VEGF")),
  # Pro inflammatory
  Proinflammatory = filter_features(srat, c("IL1A", "IL1B", "IFNG", "TBX21", "CCL3", "CCL4", "PRF1", "GZMA", "GZMB", "GZMK", "GZMH", "CD8A", "FASLG", "CCL2", "CCL20", "IL2", "IL6", "IL12A", "IL17A", "IL23A", "PTGS2", "TLR4")),
  # Anti-inflammatory
  Antiinflammatory = filter_features(srat, c("TIGIT", "IDO1", "LGALS3", "PDCD1", "FOXP3", "ENTPD1", "CD274", "CSF2", "CTLA4", "CXCL12", "CXCL5", "IL8", "MIF", "PTGS2", "VEGFA")),
  # type I interferon response
  Type1_interferon = filter_features(srat, c("IRF1", "IFIH1", "IFITM3", "DDX58", "IFI44L", "IFI6", "IFITM2", "NAMPT", "OASL", "RTP4", "TREX1", "ADAR", "FAM46C", "LY6E", "MCOLN2", "APOBEC3G", "IL15", "ISG15", "MX1", "TLR3")),
  # Type II interferon response
  Type2_interferon = filter_features(srat, c("IFNG", "CXCL9", "CXCL10", "STAT1", "CD274", "P21", "MYC", "SMAD7", "IRF1")),
  # anergy
  Anergy = filter_features(srat, c("EGR3", "NR4A3", "EGR1", "NR4A2", "EGR2", "TNFSF11", "IRF4", "GCH1", "GADD45B", "NFATC1", "JARID2", "SLC29A3", "HLF", "ZFP36L1", "RNF19A", "ADORA2B", "CCRN41", "DUSP6", "NDRG1", "ADORA2A", "HSPA1A", "PFKP", "FYN", "CTSE", "ZFP629", "F2R", "RNF128", "LAG3", "RGS16", "E2F1", "E2F2")),
  # Bystander
  bystander = filter_features(srat, c("ENTPD1", "ITGAE", "KLRK1", "PECAM1", "NCR3", "KLRG1", "TLR2", "TLR4", "TLR7", "TLR9"))
  # T Cell Exhaustion
  #,T_Exhaustion = filter_features(srat, c("ADGRG1", "AFAP1L2", "CCND2", "CD38", "CD8A", "CD8B", "CHST12", "CTLA4", "DFNB31", "EOMES", "FUT8", "ITM2A", "LAG3", "MYO1E", "NDFIP2", "PARK7", "PDCD1", "SIRPG", "SNX9"))
)

set.seed(1)
srat = AddModuleScore(srat, features = markers, name = 'program')
mat_all = srat@meta.data %>%
  #rownames_to_column("barcode") %>%
  dplyr::select(level_2, Origin2_n, starts_with('program')) %>%
  pivot_longer(starts_with("program"), names_to = "program", values_to = "value") %>%
  group_by(level_2, Origin2_n, program) %>%
  summarise(m = mean(value)) %>%
  pivot_wider(names_from = "program", values_from = "m")
mat_all = droplevels(mat_all)

mat_lst = split(mat_all, mat_all$level_2)
mat_lst = lapply(mat_lst, function(x){
  m = x %>%
    ungroup() %>%
    dplyr::select(-level_2) %>%
    column_to_rownames("Origin2_n")
  m = m[,paste0("program", 1:length(markers))]
  colnames(m) = names(markers)
  m = t(m)
  pheatmap:::scale_rows(m)
})
mat_lst <- mat_lst[c("Tn", "Tfh", "Treg", "Tem", "Tcm")]

# plot
value_range <- range(mat_lst)
p_lst <- lapply(1:length(mat_lst), function(i){
  mat <- mat_lst[i]
  df <- reshape2::melt(mat) %>% 
    mutate(
      Var2 = factor(Var2, levels = levels(srat$Origin2_n)),
      Var1 = factor(Var1, levels = rev(names(markers)))
    )
  df %>% 
    ggplot(aes(x = Var2, y = Var1, fill = value)) +
    geom_tile() +
    scale_y_discrete(position = "right") +
  scale_fill_gradient2(
    low = "blue", mid = "white", high = "red",
    limits = value_range
  ) +
    labs(title = names(mat_lst)[i]) +
  theme_cowplot(font_size = 6) +
  theme(
    axis.text.x = element_text(angle = 60, hjust = 1),
    axis.text.y = element_blank(),
    axis.title = element_blank(),
    axis.line = element_blank(),
    axis.ticks = element_blank(),
    text = element_text(size = 6)
  )
})
p_lst[[length(p_lst)]] <- p_lst[[length(p_lst)]] +
  theme(axis.text.y = element_text())

p_lst %>% 
  wrap_plots(nrow = 1, guides = "collect")

ggsave2(
  filename = here::here("output", DOCNAME, "Fig.CD4_functional_signature.heatmap.pdf"),
  height = 3, width = 7.5, device=cairo_pdf
)
```

## VDJ overlap

Load data

```{r load-clone, cache=FALSE, message=FALSE, warning=FALSE}
clones = read_csv('/work/home/project/scESCA/cellranger/TCR/200121_6samples.clonotype_tcr.csv')
```

Merge metadata with clonotype

```{r merge-meta-clonotypes}
clones = clones %>%
  filter(clonotype != 'None') %>%  # cells with alpha-beta pair
  mutate(clonotype_size = as.numeric(clonotype_size)) %>%
  mutate(clonal_expansion = case_when(
    clonotype_size == 1 ~ 'No',
    TRUE ~ 'Clonal'
  ))

d_4_p = cell_meta %>%
  left_join(clones, by = 'barcode') %>%
  filter(!is.na(clonotype))
```

### Origin2

```{r ov-Origin2_n, fig.width=4, fig.height=4}
PlotRepOverlap(RepOverlap(d_4_p, "Origin2_n"))

ggsave2(
  filename = here::here("output", DOCNAME, "Fig.CD4_VDJ_overlap_Origin2_n.pdf"),
  height = 4, width = 4, device = cairo_pdf
)
```




## Session info


