---
title: "00.Fig.top10_genes"
---

```{r knitr, include = FALSE}
DOCNAME <- "Fig.top10_genes"
dir.create(here::here("output", DOCNAME), showWarnings = FALSE)

NOW <- Sys.time()
# Time chunks during knitting
knitr::knit_hooks$set(timeit = function(before) {
  if (before) {
    print(paste("Start:", Sys.time()))
    NOW <<- Sys.time()
  } else {
    print(paste("Stop:", Sys.time()))
    print(Sys.time() - NOW)
  }
})

knitr::opts_chunk$set(
  autodep        = TRUE,
  cache          = FALSE,
  cache.path     = paste0("cache/", DOCNAME, "/"),
  cache.lazy     = FALSE,
  cache.comments = FALSE,
  echo           = FALSE,
  error          = FALSE,
  fig.align      = "center",
  fig.width      = 10,
  fig.height     = 8,
  message        = FALSE,
  warning        = FALSE,
  timeit         = TRUE
)
```

## Setup

Load packages

```{r libaries, cache = FALSE, message=FALSE, warning=FALSE}
# Tidyverse
library(tidyverse)

# Plotting
library(scales)
library(EnvStats)
library(ggplotify)
library(ggcorrplot)
library(ggpubr)
library(ggrepel)
library(ggrastr)

# patch
library(patchwork)
library(cowplot)
theme_set(theme_cowplot(
  font_size = 6, # Overall font size
  rel_small = 6 / 6, # axis tick labels
  rel_tiny = 6 / 6, # caption
  rel_large = 6 / 6, # title
  font_family = "Arial"
))
my_theme <- theme_cowplot(
  font_size = 6, # Overall font size
  rel_small = 6 / 6, # axis tick labels
  rel_tiny = 6 / 6, # caption
  rel_large = 6 / 6, # title
  font_family = "Arial"
)
geom.text.size <- 6 / (14 / 5)

# heatmap
library(pheatmap)
library(ComplexHeatmap)
library(circlize)

# color
library(ggsci)

# Seurat
library(Seurat)

# monocle
library(monocle3)
```

Load code

```{r source, cache = FALSE}
source(here::here("code/preprocess.R"))
source(here::here("code/glm.R"))
source(here::here("code/color.R"))
source(here::here("code/plot.R"))
```

## Endothelia

```{r , fig.width=3, fig.height=4}
cell = "endo"
CELL = "endothelia"

# c2c
fname = paste0(paste0("c2c.", cell), ".rds")
df_c2c = readRDS(here::here("data", fname))

# srat
fname = paste0(paste0("seurat_", CELL), ".rds")
srat = readRDS(here::here("output/04.rm_cells", fname))
Idents(srat) <- "level_2"

# get markers
fname = paste0(paste0("seurat_", CELL), ".markers.221116.csv")
markers <- read_csv(here::here("output/04.rm_cells", fname))

# top 10
top10 <- markers %>%
  group_by(cluster) %>%
  top_n(10, wt = avg_logFC)

# rename
top10 <- top10 %>%
  left_join(df_c2c, by = "cluster")
# de-duplicate
top10 <- top10[!duplicated(top10$gene), ]

# to list
top10_lst <- lapply(levels(top10$level_3), function(x) {
  top10 %>%
    filter(level_3 == x) %>%
    pull(gene)
})
names(top10_lst) <- levels(top10$level_3)

# get exp
mat <- AverageExpression(srat,
  assays = "RNA", features = unlist(top10_lst),
  slot = "data", verbose = F
)$RNA
mat <- log1p(as.matrix(mat))

# scale
mat_scale <- pheatmap:::scale_rows(mat)

# color
x <- ceiling(max(abs(mat_scale)))
col_fun <- circlize::colorRamp2(c(-x, 0, x), c("blue", "white", "red"))

# marker
marker_2_lab <- c(
  "FCN3",
  "ALPL"
)
# location
marker_2_lab <- sapply(marker_2_lab, function(x) {
  which(rownames(mat) == x)
}, simplify = T)
ha <- rowAnnotation(foo = anno_mark(
  at = marker_2_lab,
  labels = names(marker_2_lab),
  labels_gp = gpar(fontsize = 6)
))

ht <- Heatmap(mat_scale,
  name = "Exp.",
  col = col_fun,
  right_annotation = ha,
  cluster_columns = F,
  cluster_rows = F,
  show_row_names = FALSE,
  column_names_gp = gpar(fontsize = 6),
  # column_names_rot = 60,
  heatmap_legend_param = list( # direction = "horizontal",
    labels_gp = gpar(fontsize = 6),
    title_gp = gpar(fontsize = 6),
    # title_position = "leftcenter",
    grid_height = unit(2, "mm"),
    grid_width = unit(2, "mm")
  )
)
# draw(ht, heatmap_legend_side = "bottom")
p.markers.top10 <- plot_grid(grid.grabExpr(draw(ht, heatmap_legend_side = "right")))
p.markers.top10
```

## Fibroblasts

```{r , fig.width=3, fig.height=4}
cell = "fib"
CELL = "fibroblasts"

# c2c
fname = paste0(paste0("c2c.", cell), ".rds")
df_c2c = readRDS(here::here("data", fname))

# srat
fname = paste0(paste0("seurat_", CELL), ".rds")
srat = readRDS(here::here("output/04.rm_cells", fname))
Idents(srat) <- "level_3"

# get markers
fname = paste0(paste0("seurat_", CELL), ".markers.221116.csv")
markers <- read_csv(here::here("output/04.rm_cells", fname))

# top 10
top10 <- markers %>%
  group_by(cluster) %>%
  top_n(10, wt = avg_logFC)

# rename
top10 <- top10 %>%
  left_join(df_c2c, by = "cluster")
# de-duplicate
top10 <- top10[!duplicated(top10$gene), ]

# to list
top10_lst <- lapply(levels(top10$level_3), function(x) {
  top10 %>%
    filter(level_3 == x) %>%
    pull(gene)
})
names(top10_lst) <- levels(top10$level_3)

# get exp
mat <- AverageExpression(srat,
  assays = "RNA", features = unlist(top10_lst),
  slot = "data", verbose = F
)$RNA
mat <- log1p(as.matrix(mat))

# scale
mat_scale <- pheatmap:::scale_rows(mat)

# color
x <- ceiling(max(abs(mat_scale)))
col_fun <- circlize::colorRamp2(c(-x, 0, x), c("blue", "white", "red"))

# marker
marker_2_lab <- c(
  "CFD",
  "FABP3"
)
# location
marker_2_lab <- sapply(marker_2_lab, function(x) {
  which(rownames(mat) == x)
}, simplify = T)
ha <- rowAnnotation(foo = anno_mark(
  at = marker_2_lab,
  labels = names(marker_2_lab),
  labels_gp = gpar(fontsize = 6)
))

ht <- Heatmap(mat_scale,
  name = "Exp.",
  col = col_fun,
  right_annotation = ha,
  cluster_columns = F,
  cluster_rows = F,
  show_row_names = FALSE,
  column_names_gp = gpar(fontsize = 6),
  # column_names_rot = 60,
  heatmap_legend_param = list( # direction = "horizontal",
    labels_gp = gpar(fontsize = 6),
    title_gp = gpar(fontsize = 6),
    # title_position = "leftcenter",
    grid_height = unit(2, "mm"),
    grid_width = unit(2, "mm")
  )
)
# draw(ht, heatmap_legend_side = "bottom")
p.markers.top10 <- plot_grid(grid.grabExpr(draw(ht, heatmap_legend_side = "right")))
p.markers.top10
```

## B cells

```{r , fig.width=3, fig.height=4}
cell = "b"
CELL = "bcells"

# c2c
fname = paste0(paste0("c2c.", cell), ".rds")
df_c2c = readRDS(here::here("data", fname))

# srat
fname = paste0(paste0("seurat_", CELL), ".rds")
srat = readRDS(here::here("output/04.rm_cells", fname))
Idents(srat) <- "level_2"

# get markers
fname = paste0(paste0("seurat_", CELL), ".markers.221116.csv")
markers <- read_csv(here::here("output/04.rm_cells", fname)) %>%
  mutate(cluster = as.factor(cluster))

# top 10
top10 <- markers %>%
  group_by(cluster) %>%
  top_n(10, wt = avg_logFC)

# rename
top10 <- top10 %>%
  left_join(df_c2c, by = "cluster")
# de-duplicate
top10 <- top10[!duplicated(top10$gene), ]

# to list
top10_lst <- lapply(levels(top10$level_3), function(x) {
  top10 %>%
    filter(level_3 == x) %>%
    pull(gene)
})
names(top10_lst) <- levels(top10$level_3)

# get exp
mat <- AverageExpression(srat,
  assays = "RNA", features = unlist(top10_lst),
  slot = "data", verbose = F
)$RNA
mat <- log1p(as.matrix(mat))

# scale
mat_scale <- pheatmap:::scale_rows(mat)

# color
x <- ceiling(max(abs(mat_scale)))
col_fun <- circlize::colorRamp2(c(-x, 0, x), c("blue", "white", "red"))

# marker
marker_2_lab <- c(
  "LMNA",
  "IRF7"
)
# location
marker_2_lab <- sapply(marker_2_lab, function(x) {
  which(rownames(mat) == x)
}, simplify = T)
ha <- rowAnnotation(foo = anno_mark(
  at = marker_2_lab,
  labels = names(marker_2_lab),
  labels_gp = gpar(fontsize = 6)
))

ht <- Heatmap(mat_scale,
  name = "Exp.",
  col = col_fun,
  right_annotation = ha,
  cluster_columns = F,
  cluster_rows = F,
  show_row_names = FALSE,
  column_names_gp = gpar(fontsize = 6),
  # column_names_rot = 60,
  heatmap_legend_param = list( # direction = "horizontal",
    labels_gp = gpar(fontsize = 6),
    title_gp = gpar(fontsize = 6),
    # title_position = "leftcenter",
    grid_height = unit(2, "mm"),
    grid_width = unit(2, "mm")
  )
)
# draw(ht, heatmap_legend_side = "bottom")
p.markers.top10 <- plot_grid(grid.grabExpr(draw(ht, heatmap_legend_side = "right")))
p.markers.top10
```

## Myeloid cells

```{r , fig.width=3, fig.height=4}
cell = "mye"
CELL = "myeloid"

# c2c
fname = paste0(paste0("c2c.", cell), ".rds")
df_c2c = readRDS(here::here("data", fname))

# srat
fname = paste0(paste0("seurat_", CELL), ".rds")
srat = readRDS(here::here("output/04.rm_cells", fname))
Idents(srat) <- "level_3"

# get markers
fname = paste0(paste0("seurat_", CELL), ".markers.221116.csv")
markers <- read_csv(here::here("output/04.rm_cells", fname)) %>%
  mutate(cluster = as.factor(cluster))

# top 10
top10 <- markers %>%
  group_by(cluster) %>%
  top_n(10, wt = avg_logFC)

# rename
top10 <- top10 %>%
  left_join(df_c2c, by = "cluster")
# de-duplicate
top10 <- top10[!duplicated(top10$gene), ]

# to list
top10_lst <- lapply(levels(top10$level_3), function(x) {
  top10 %>%
    filter(level_3 == x) %>%
    pull(gene)
})
names(top10_lst) <- levels(top10$level_3)

# get exp
mat <- AverageExpression(srat,
  assays = "RNA", features = unlist(top10_lst),
  slot = "data", verbose = F
)$RNA
mat <- log1p(as.matrix(mat))

# scale
mat_scale <- pheatmap:::scale_rows(mat)

# color
x <- ceiling(max(abs(mat_scale)))
col_fun <- circlize::colorRamp2(c(-x, 0, x), c("blue", "white", "red"))

# marker
marker_2_lab <- c(
  "LMNA",
  "IRF7"
)
# location
marker_2_lab <- sapply(marker_2_lab, function(x) {
  which(rownames(mat) == x)
}, simplify = T)
ha <- rowAnnotation(foo = anno_mark(
  at = marker_2_lab,
  labels = names(marker_2_lab),
  labels_gp = gpar(fontsize = 6)
))

ht <- Heatmap(mat_scale,
  name = "Exp.",
  col = col_fun,
  right_annotation = ha,
  cluster_columns = F,
  cluster_rows = F,
  show_row_names = FALSE,
  column_names_gp = gpar(fontsize = 6),
  # column_names_rot = 60,
  heatmap_legend_param = list( # direction = "horizontal",
    labels_gp = gpar(fontsize = 6),
    title_gp = gpar(fontsize = 6),
    # title_position = "leftcenter",
    grid_height = unit(2, "mm"),
    grid_width = unit(2, "mm")
  )
)
# draw(ht, heatmap_legend_side = "bottom")
p.markers.top10 <- plot_grid(grid.grabExpr(draw(ht, heatmap_legend_side = "right")))
p.markers.top10
```


## T cells

```{r , fig.width=3, fig.height=4}
cell = "t"
CELL = "tcells"

# c2c
fname = paste0(paste0("c2c.", cell), ".rds")
df_c2c = readRDS(here::here("data", fname))

# srat
fname = paste0(paste0("seurat_", CELL), ".rds")
srat = readRDS(here::here("output/04.rm_cells", fname))
Idents(srat) <- "level_3"

# get markers
fname = paste0(paste0("seurat_", CELL), ".markers.221116.csv")
markers <- read_csv(here::here("output/04.rm_cells", fname))

# top 10
top10 <- markers %>%
  group_by(cluster) %>%
  top_n(10, wt = avg_logFC)

# rename
top10 <- top10 %>%
  left_join(df_c2c, by = "cluster")
# de-duplicate
top10 <- top10[!duplicated(top10$gene), ]

# to list
top10_lst <- lapply(levels(top10$level_3), function(x) {
  top10 %>%
    filter(level_3 == x) %>%
    pull(gene)
})
names(top10_lst) <- levels(top10$level_3)

# get exp
mat <- AverageExpression(srat,
  assays = "RNA", features = unlist(top10_lst),
  slot = "data", verbose = F
)$RNA
mat <- log1p(as.matrix(mat))

# scale
mat_scale <- pheatmap:::scale_rows(mat)

# color
x <- ceiling(max(abs(mat_scale)))
col_fun <- circlize::colorRamp2(c(-x, 0, x), c("blue", "white", "red"))

# marker
marker_2_lab <- c(
  "LMNA",
  "CCR7"
)
# location
marker_2_lab <- sapply(marker_2_lab, function(x) {
  which(rownames(mat) == x)
}, simplify = T)
ha <- rowAnnotation(foo = anno_mark(
  at = marker_2_lab,
  labels = names(marker_2_lab),
  labels_gp = gpar(fontsize = 6)
))

ht <- Heatmap(mat_scale,
  name = "Exp.",
  col = col_fun,
  right_annotation = ha,
  cluster_columns = F,
  cluster_rows = F,
  show_row_names = FALSE,
  column_names_gp = gpar(fontsize = 6),
  # column_names_rot = 60,
  heatmap_legend_param = list( # direction = "horizontal",
    labels_gp = gpar(fontsize = 6),
    title_gp = gpar(fontsize = 6),
    # title_position = "leftcenter",
    grid_height = unit(2, "mm"),
    grid_width = unit(2, "mm")
  )
)
# draw(ht, heatmap_legend_side = "bottom")
p.markers.top10 <- plot_grid(grid.grabExpr(draw(ht, heatmap_legend_side = "right")))
p.markers.top10
```

## Session info




