---
title: "monocle3.fib.par_1.NMF-C1_C2_iCAF-C3"
---

Run on T01

```{r knitr, include = FALSE}
DOCNAME = "monocle3.fib.par_1.NMF-C1_C2_iCAF-C3"
dir.create(here::here("output", DOCNAME), showWarnings = FALSE)

NOW <- Sys.time()
# Time chunks during knitting
knitr::knit_hooks$set(timeit = function(before) {
    if (before) {
        print(paste("Start:", Sys.time()))
        NOW <<- Sys.time()
    } else {
        print(paste("Stop:", Sys.time()))
        print(Sys.time() - NOW)
    }
})

knitr::opts_chunk$set(
    autodep        = TRUE,
    cache          = FALSE,
    cache.path     = paste0("cache/", DOCNAME, "/"),
    cache.lazy     = FALSE, 
    cache.comments = FALSE,
    echo           = FALSE,
    error          = FALSE,
    fig.align      = "center",
    fig.width      = 10,
    fig.height     = 8,
    message        = FALSE,
    warning        = FALSE,
    timeit         = TRUE
)
```

## Setup

Load packages

```{r libaries, cache = FALSE, warning=FALSE, message=FALSE}
# Tidyverse
library(tidyverse)

# Plotting
library(ggcorrplot)
library(pheatmap)
library(ComplexHeatmap)
library(circlize)
library(ggpubr)
library(ggplotify)
library(ggrepel)

# patch
library(cowplot)
theme_set(theme_cowplot(font_size = 10,
                        rel_small = 10/10,
                        rel_tiny = 8/10,
                        rel_large = 10/10,
                        font_family = "Arial"))
library(patchwork)

# color
library(ggsci)

# Seurat
library(Seurat)

# monocle
library(SeuratWrappers)
library(monocle3)
```

```{r source, cache = FALSE}
source(here::here("code/preprocess.R"))
source(here::here("code/color.R"))
source(here::here("code/plot.R"))
```

Load rds (save time)

```{r load-rds, cache=FALSE}
cds_sub = readRDS(here::here("output", DOCNAME, "cds_sub.rds"))
cds_sub
```

## monocle3

Subset NMF-C1 -> NMF-C2 -> iCAF-C3

```{r eval=FALSE}
cds = readRDS(here::here('output/04.rm_cells/monocle3_fibroblasts.par_1.rds'))
cds

cds_sub = cds[,colData(cds) %>%
  as.data.frame() %>%
  filter(level_3 %in% c("NMF-C1", "NMF-C2", "iCAF-C3")) %>% #head()
  row.names]

saveRDS(cds_sub, file = here::here("output", DOCNAME, "cds_sub.rds"))
```

Get genes significantly vary as a function of time

```{r eval=FALSE}
ciliated_cds_pr_test_res <- graph_test(cds_sub, neighbor_graph="principal_graph", cores=4)
ciliated_cds_pr_test_res = ciliated_cds_pr_test_res %>%
    arrange(-morans_I)
saveRDS(ciliated_cds_pr_test_res, file = here::here("output", DOCNAME, "ciliated_cds_pr_test_res.rds"))

ciliated_cds_pr_test_res %>%
  rownames_to_column("gene") %>% 
  write_tsv(here::here("output", DOCNAME, 'monocle3.fib.par_1.NMF-C1_C2_iCAF-C3.graph_test.tsv'))
```

## Genes

Show

```{r}
ciliated_cds_pr_test_res = readRDS(here::here("output", DOCNAME, "ciliated_cds_pr_test_res.rds"))

pr_graph_test_res = subset(ciliated_cds_pr_test_res, q_value < 0.01 & morans_I > 0.2)
pr_deg_ids <- row.names(pr_graph_test_res)
DT::datatable(pr_graph_test_res, filter = "top")
```


Plot genes (top 100) along pseudotime

```{r plot-genes-pseudotime, fig.width=7, fig.height=10}
pt.matrix <- exprs(cds_sub)[match(pr_deg_ids[1:100], rownames(rowData(cds_sub))), order(pseudotime(cds_sub))]
#Can also use "normalized_counts" instead of "exprs" to use various normalization methods, for example:
#normalized_counts(cds, norm_method = "log")

pt.matrix <- t(apply(pt.matrix,1,function(x){smooth.spline(x,df=3)$y}))
pt.matrix <- t(apply(pt.matrix,1,function(x){(x-mean(x))/sd(x)}))
rownames(pt.matrix) <- pr_deg_ids[1:100]

pt.matrix = na.omit(pt.matrix)
#Ward.D2 Hierarchical Clustering
hthc <- Heatmap(
  pt.matrix,
  name                         = "z-score",
  col                          = colorRamp2(seq(from=-2,to=2,length=11),
                                            rev(brewer.pal(11, "Spectral"))),
  show_row_names               = TRUE,
  show_column_names            = FALSE,
  row_names_gp                 = gpar(fontsize = 8),
  row_title_rot                = 0,
  cluster_rows                 = TRUE,
  clustering_method_rows       = "ward.D2",
  cluster_row_slices           = FALSE,
  cluster_columns              = FALSE,
  row_km = 2)
draw(hthc)
```

## Plot selected

Genes selected by Zhang

```{r}
pt.matrix <- exprs(cds_sub)[match(pr_deg_ids, rownames(rowData(cds_sub))), order(pseudotime(cds_sub))]
#Can also use "normalized_counts" instead of "exprs" to use various normalization methods, for example:
#normalized_counts(cds, norm_method = "log")

pt.matrix <- t(apply(pt.matrix,1,function(x){smooth.spline(x,df=3)$y}))
pt.matrix <- t(apply(pt.matrix,1,function(x){(x-mean(x))/sd(x)}))
rownames(pt.matrix) <- pr_deg_ids

x = pseudotime(cds_sub)
cells = names(x)[order(x)]
colnames(pt.matrix) = cells

pt.matrix = na.omit(pt.matrix)
pt.matrix[1:3, 1:3]
```

sort

```{r}
# order
a = order(apply(pt.matrix, 1, FUN = function(i){
  which(i == max(i))
}))
pt.matrix = pt.matrix[a, ]
pt.matrix[1:3, 1:3]
```

anno

```{r}
anno = as.data.frame(colData(cds_sub)[colnames(pt.matrix), c("Origin4", "level_3")])
anno = droplevels(anno)
head(anno)
```

heatmap row anno

```{r}
gene_selected = c("UAP1", "CFD", "TIMP3", "SOD3", "IGFBP6", "CST3", "FOS", "GPX3", "ZFP36", "JUNB", "JUN", "FBN1", "DCN", "CD55", "MDK", "ISG15", "IGF1", "THBS2", "ADAM12", "BGN", "POSTN", "LOX", "RGS5", "IGFBP7", "SPARC", "CXCL2", "NR4A2", "HES1", "RUNX1", "IFI27", "IFI6", "CXCL14", "VCAN", "PDPN", "SOD2", "THBS1", "C7", "A2M")

# marker
marker_2_lab = intersect(gene_selected, pr_deg_ids)
# location
marker_2_lab = sapply(marker_2_lab, function(x){which(rownames(pt.matrix) == x)}, simplify = T)
ha = rowAnnotation(foo = anno_mark(at = marker_2_lab,
                                   labels = names(marker_2_lab),
                                   labels_gp = gpar(fontsize = 6)))
```

heatmap col anno

```{r}
col_ha = HeatmapAnnotation(
  df = anno,
  annotation_name_gp = gpar(fontsize = 6),
  col = list(
      Origin4 = origin4_color_maps[levels(anno$Origin4)],
      level_3 = fib_level_3_color[levels(anno$level_3)]
    )
)
```

plot

```{r fig.width=6, fig.height=6}
hthc <- Heatmap(
  pt.matrix,
  name                         = "z-score",
  col                          = colorRamp2(seq(from=-2,to=2, length=11),
                                            rev(brewer.pal(11, "Spectral"))),
  show_row_names               = FALSE,
  show_column_names            = FALSE,
  right_annotation = ha,
  top_annotation = col_ha,
  row_names_gp                 = gpar(fontsize = 8),
  row_title_rot                = 0,
  cluster_rows                 = FALSE,
  clustering_method_rows       = "ward.D2",
  cluster_row_slices           = FALSE,
  cluster_columns              = FALSE)
draw(hthc)
```


## Session info
