---
title: "monocle3.fib.par_1"
---

```{r knitr, include = FALSE}
DOCNAME = "monocle3.fib.par_1"
dir.create(here::here("output", DOCNAME), showWarnings = FALSE)

NOW <- Sys.time()
# Time chunks during knitting
knitr::knit_hooks$set(timeit = function(before) {
    if (before) {
        print(paste("Start:", Sys.time()))
        NOW <<- Sys.time()
    } else {
        print(paste("Stop:", Sys.time()))
        print(Sys.time() - NOW)
    }
})

knitr::opts_chunk$set(
    autodep        = TRUE,
    cache          = FALSE,
    cache.path     = paste0("cache/", DOCNAME, "/"),
    cache.lazy     = FALSE, 
    cache.comments = FALSE,
    echo           = FALSE,
    error          = FALSE,
    fig.align      = "center",
    fig.width      = 10,
    fig.height     = 8,
    message        = FALSE,
    warning        = FALSE,
    timeit         = TRUE
)
```

## Setup

Load packages

```{r libaries, cache = FALSE, warning=FALSE, message=FALSE}
# Tidyverse
library(tidyverse)

# Plotting
library(ggcorrplot)
library(pheatmap)
library(ComplexHeatmap)
library(circlize)
library(ggpubr)
library(ggplotify)
library(ggrepel)

# patch
library(cowplot)
theme_set(theme_cowplot(font_size = 12,
                        rel_small = 10/12,
                        rel_tiny = 8/12,
                        rel_large = 12/12,
                        font_family = "Arial"))
library(patchwork)

# color
library(ggsci)

# fonts
library(extrafont)
#font_import()
#font_import(paths = "/T02Data/niuyw/.local/share/fonts")
loadfonts(device = "pdf", quiet = TRUE)

# Seurat
library(Seurat)

# monocle
library(SeuratWrappers)
library(monocle3)
```

```{r source, cache = FALSE}
source(here::here("code/preprocess.R"))
source(here::here("code/color.R"))
source(here::here("code/plot.R"))
```

Load rds (save time)

```{r load-rds, cache=FALSE}
# Load seurat
seurat = readRDS(here::here('output', DOCNAME, 'seurat_fib.par_1.rds'))
seurat
cds = readRDS(here::here('output', DOCNAME, 'monocle3_fib.par_1.rds'))
cds
```

## Build cds

```{r build-cds, cache=FALSE, eval=FALSE}
# Load seurat
seurat = readRDS(here::here('output/04.rm_cells/seurat_fibroblasts.rds'))
seurat

# subset: par_1
srat_subset = subset(seurat, subset = level_2 %in% c("NMF", "iCAF"))
get_vars <- function(seurat_obj) {
  vst_each = c()
  source = FetchData(seurat_obj, vars = c('Source'))
  for (i in unique(seurat_obj$Source)) {
    x = seurat_obj[,which(source == i)]
    if (dim(x)[2] < 100) {
      next
    } else {
      x = FindVariableFeatures(x, selection.method = 'vst', nfeatures = 500)
      vst_each = c(VariableFeatures(x), vst_each)
    }
  }
  VariableFeatures(seurat_obj) = unique(vst_each)
  return(seurat_obj)
}
srat_subset = get_vars(srat_subset)
vars.to.regress = c('nCount_RNA', 'percent.mt', 'percent.ribo', 'percent.dissociation',
                    'percent.heat', 'CC.Difference')
srat_subset <- ScaleData(srat_subset, features = VariableFeatures(srat_subset),
                         vars.to.regress = vars.to.regress, verbose = F)
srat_subset = RunPCA(srat_subset, features = VariableFeatures(srat_subset), verbose = F)
n_pc = min(determine_pc_num(srat_subset))
# non-linear dimensional reduction (UMAP/tSNE)
srat_subset = RunUMAP(srat_subset, dims = 1:n_pc, verbose = F)
saveRDS(srat_subset, file = here::here('output', DOCNAME, "seurat_fib.par_1.rds"))

# to h5ad
sceasy::convertFormat(srat_subset, from="seurat", to="anndata",
                      main_layer = 'counts',
                      outFile=here::here('output', DOCNAME, paste0('seurat_fib.par_1', '.h5ad')))

# to cds
cds = as.cell_data_set(srat_subset)

# Cluster cells
cds <- cluster_cells(cds)

# Constructing trajectories
cds <- learn_graph(cds)

# pseudotime
# NMF-C1 markers
max.avp <- which.max(unlist(FetchData(srat_subset, "WIF1")))
max.avp <- colnames(srat_subset)[max.avp]
cds <- order_cells(cds, root_cells = max.avp)
data.frame(cell = names(pseudotime(cds)), Pseudotime = pseudotime(cds)) %>%
  write_csv(file = here::here('output/04.rm_cells/monocle3_fib.par_1.pseudotime.csv'))

# save
saveRDS(cds, file = here::here('output', DOCNAME, 'monocle3_fib.par_1.rds'))
```

## Cluster

Cluster by Seurat or Monocle3

```{r plot-cluster, fig.width=12, fig.height=5, warning=FALSE}
# plot labeled by seurat clusters
p1 = DimPlot(seurat, group.by = 'level_2') +
  scale_color_manual(values = fib_level_2_color) +
  labs(title = "Seurat level_2")
p2 = plot_cells(cds, color_cells_by = "partition",
                show_trajectory_graph = FALSE,
                group_label_size = 3) +
  labs(title = "Monocle3 partition")
p1 + p2
```

## Trajectory {.tabset}

### Level 3

No leaves

```{r Trajectory-level-3, fig.width=6, fig.height=5}
plot_cells(cds, label_groups_by_cluster = FALSE,
           color_cells_by = "level_3",
           cell_size = .7,
           group_label_size = 3,
           label_branch_points = TRUE,
           label_leaves = FALSE) +
  scale_color_manual(values = fib_level_3_color)
```

With leaves

```{r , fig.width=6, fig.height=5}
plot_cells(cds, label_groups_by_cluster = FALSE,
           color_cells_by = "level_3",
           cell_size = .7,
           group_label_size = 3,
           label_branch_points = TRUE,
           label_leaves = TRUE) +
  scale_color_manual(values = fib_level_3_color)
```

### partition

No leaves

```{r Trajectory, fig.width=6, fig.height=5}
plot_cells(cds, label_groups_by_cluster = FALSE,
           color_cells_by = "partition",
           cell_size = .7,
           group_label_size = 3,
           label_branch_points = TRUE,
           label_leaves = FALSE)
```

With leaves

```{r , fig.width=6, fig.height=5}
plot_cells(cds, label_groups_by_cluster = FALSE,
           color_cells_by = "partition",
           cell_size = .7,
           group_label_size = 3,
           label_branch_points = TRUE,
           label_leaves = TRUE)
```

## Pseudotime

Plot pseudotime

```{r par_1-pseudotime, message=FALSE, warning=FALSE, fig.width=12, fig.height=5}
p1 = plot_cells(cds, color_cells_by = "partition",
           label_leaves = FALSE,
           label_branch_points = TRUE)
p2 = plot_cells(cds, color_cells_by = "pseudotime",
           label_cell_groups = FALSE, label_leaves = FALSE, 
           label_branch_points = TRUE)
p1 + p2
```

## Session info


